version: "3.5"
services:
  thmonitor.nodokamome.com:
    build: .
    image: thmonitor.nodokamome.com
    container_name: thmonitor.nodokamome.com
    tty: true
    restart: always
    volumes:
      - ./src:/src
    command: [sh, -c, npm install && npm run start]
    environment:
      - TZ=Asia/Tokyo
      - VIRTUAL_HOST=thmonitor.nodokamome.com
      - LETSENCRYPT_HOST=thmonitor.nodokamome.com
      - LETSENCRYPT_EMAIL=mail@nodokamome.com
    ports: 
      - 3001:3000
    networks:
      - proxy-network # プロキシネットワーク
      - app-network # アプリネットワーク

# プロキシネットワーク、アプリネットワークと接続
networks:
  proxy-network:
    name: proxy_network
  app-network:
    name: app_network
